export const OperatorActionTypes = {
    GET_OPERTORS_SUCCESS: 'GET_OPERTORS_SUCCESS',
    GET_OPERTORS_FAIL: 'GET_OPERTORS_FAIL',

    ADD_OPERATOR_START: 'ADD_OPERATOR_START',
    ADD_OPERATOR_SUCCESS: 'ADD_OPERATOR_SUCCESS',
    ADD_OPERATOR_FAIL: 'ADD_OPERATOR_FAIL',
    ADD_OPERATOR_CLOSE: 'ADD_OPERATOR_CLOSE',
    SEARCH_OPERATORS: 'SEARCH_OPERATORS',
    EDIT_OPERATOR_START: 'EDIT_OPERATOR_START',
    EDIT_OPERATOR_SUCCESS: 'EDIT_OPERATOR_SUCCESS',
    EDIT_OPERATOR_FAIL: 'EDIT_OPERATOR_FAIL',
    EDIT_OPERATOR_CLOSE: 'EDIT_OPERATOR_CLOSE'
  };